'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const STORE='pocket-grand-prix-v1';
const fresh=()=>({credits:1200,xp:0,upgrades:[0,0,0,0,0,0],era:0,color:0,helmet:0,suit:0,races:0,wins:0,bestLap:null,history:[]});
let save=fresh();try{const p=JSON.parse(localStorage.getItem(STORE));if(p&&Array.isArray(p.upgrades)){save={...save,...p};save.upgrades=Array.from({length:6},(_,i)=>Math.max(0,Math.min(3,Number(p.upgrades[i])||0)));}}catch{}
let tab='race',sound=false,audio,osc,gain;
const colors=[['Rosso red','#e33830',0],['Alpine blue','#428aaa',1],['British green','#477657',2],['Sunburst','#e9ad32',3],['Pearl white','#ebeee3',2]];
const helmets=[['Acid yellow','#dfff60',1],['Scarlet','#e33830',1],['Ice blue','#81cddd',2],['Champion gold','#d7ac4d',3]];
const suits=[['Factory red','#e33830',1],['Midnight','#283d43',1],['Ivory','#e7eadd',2],['Heritage green','#447354',3]];
const eras=['Classic','Evolution','Modern'];
const parts=[['◉','Tires & wheels','Grip, corner speed & new wheel finish'],['◫','Brakes','Shorter stopping distance'],['ϟ','Engine','More power & higher top speed'],['⚙','Transmission','Faster acceleration out of corners'],['⌁','Wing','Downforce & high-speed control'],['⏚','Suspension','Sharper steering & reduced grass penalty']];
const level=()=>Math.min(3,1+Math.floor(save.xp/300));
const money=n=>n.toLocaleString();
function persist(){try{localStorage.setItem(STORE,JSON.stringify(save));}catch{toast('Browser storage unavailable. Keep this tab open to retain progress.');}updateProfile();}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),3200);}
function tint(){return ['none','hue-rotate(180deg)','hue-rotate(100deg) saturate(.7)','hue-rotate(43deg)','saturate(0) brightness(1.4)'][save.color]||'none';}
function updateProfile(){const l=level();$('#credits').textContent=money(save.credits);$('#level').textContent='0'+l;$('#rank').textContent=['Rookie racer','Club contender','Grand prix ace'][l-1];$('#xp').textContent=l===3?save.xp+' XP · MAX LEVEL':save.xp%300+' / 300 XP';$('#xpbar').style.width=(l===3?100:save.xp%300/3)+'%';$('#nextlevel').textContent=l===3?'ALL CLASSES UNLOCKED':'NEXT: LEVEL '+(l+1);$('#heroCar').src='public/assets/car'+(save.era?'-'+save.era:'')+'.png';$('#heroCar').style.filter=tint()+' drop-shadow(0 15px 10px #20332a30)';$('#carname').textContent=['The original','The contender','The front runner'][save.era];$('.tag').textContent=['MK I','MK II','MK III'][save.era];$('#liveryName').textContent=colors[save.color][0];$('.car-dot').style.background=colors[save.color][1];$('.garage-bottom strong').innerHTML=eras[save.era]+' chassis <span>Level '+(save.era+1)+'</span>';$('.garage-bottom>span').textContent='0'+(save.era+1)+' / 03';}
function setTab(t){tab=t;$$('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===t);b.setAttribute('aria-current',b.dataset.tab===t?'page':'false');});$('#drawer').hidden=t==='race';if(t!=='race')renderDrawer();window.scrollTo(0,0);}
$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$$('[data-open]').forEach(b=>b.onclick=()=>setTab(b.dataset.open));$('.brand').onclick=e=>{e.preventDefault();setTab('race');};
const cost=i=>[250,200,350,280,250,220][i]*(save.upgrades[i]+1);
function swatches(list,key){return '<div class="swatches">'+list.map((v,i)=>`<button class="swatch ${save[key]===i?'selected':''}" data-cosmetic="${key}" data-index="${i}" ${level()<v[2]?'disabled':''}><i style="background:${v[1]}"></i><span>${v[0]}${level()<v[2]?' · Lv '+v[2]:''}</span></button>`).join('')+'</div>';}
function renderDrawer(){let html=`<div class="drawer-head"><div><span class="eyebrow">POCKET MOTORSPORT / ${tab.toUpperCase()}</span><h1>${{car:'Built to be yours.',driver:'Suit up. Stand out.',stats:'Every lap counts.'}[tab]}</h1><p class="sub">${{car:'Small changes. A different machine. Upgrades carry across all chassis.',driver:'Your identity, from the paddock to the podium. Unlock more by racing.',stats:'Your racing career, saved on this browser.'}[tab]}</p></div><button class="close" id="closeDrawer">Back ↗</button></div>`;
if(tab==='car')html+=`<div class="garage-layout"><div><div class="garage-show"><img src="public/assets/car${save.era?'-'+save.era:''}.png" alt="Your customized car" style="filter:${tint()}"><div class="era-options">${eras.map((e,i)=>`<button data-era="${i}" class="${i===save.era?'selected':''}" ${i>=level()?'disabled':''}>MK ${['I','II','III'][i]} · ${e}<br><small>${i>=level()?'Unlock at level '+(i+1):i===save.era?'Equipped':'Equip'}</small></button>`).join('')}</div></div><div class="cosmetic-section"><h3>Livery</h3>${swatches(colors,'color')}</div></div><div class="upgrades">${parts.map((p,i)=>`<div class="upgrade"><span class="part-icon">${p[0]}</span><div class="upgrade-info"><h3>${p[1]}</h3><p>${p[2]}</p><div class="pips">${[0,1,2].map(n=>`<i class="${n<save.upgrades[i]?'on':''}"></i>`).join('')}</div></div><button data-upgrade="${i}" ${save.upgrades[i]>=3||save.credits<cost(i)?'disabled':''}>${save.upgrades[i]>=3?'Maxed':'◈ '+money(cost(i))}</button></div>`).join('')}<p class="sub">Level 2: Evolution chassis · Level 3: Modern chassis<br>Every upgrade has 3 tiers. Earn credits by finishing races.</p></div></div>`;
if(tab==='driver')html+=`<div class="driver-preview"><div class="driver-doll" style="--helmet:${helmets[save.helmet][1]};--suit:${suits[save.suit][1]}"><div class="helmet"></div><div class="suit"></div></div><div><h3>Helmet collection</h3>${swatches(helmets,'helmet')}<div class="cosmetic-section"><h3>Race suits</h3>${swatches(suits,'suit')}</div><p class="sub">Your chosen helmet and suit appear in your car on track.</p></div></div>`;
if(tab==='stats')html+=`<div class="stat-grid">${[[save.races,'Races completed'],[save.wins,'Race wins'],[save.bestLap?fmt(save.bestLap):'—','Personal best lap'],[save.xp,'Career XP']].map(s=>`<div class="stat"><strong>${s[0]}</strong><span>${s[1]}</span></div>`).join('')}</div><h3 style="margin-top:35px">Recent races</h3>${save.history.length?`<table class="history"><thead><tr><th>CIRCUIT</th><th>POSITION</th><th>TIME</th><th>CREDITS</th></tr></thead><tbody>${save.history.slice(0,8).map(r=>`<tr><td>${r.circuit||'Verdant Circuit'}</td><td>P${r.position} / 6</td><td>${fmt(r.time)}</td><td>+${r.reward}</td></tr>`).join('')}</tbody></table>`:'<p class="sub">An empty record. A whole career ahead. Your first finish starts the story.</p>'}`;
$('#drawer').innerHTML=html;$('#closeDrawer').onclick=()=>setTab('race');$$('[data-upgrade]').forEach(b=>b.onclick=()=>{const i=+b.dataset.upgrade;if(save.upgrades[i]>=3||save.credits<cost(i))return;save.credits-=cost(i);save.upgrades[i]++;persist();renderDrawer();toast(parts[i][1]+' upgraded to tier '+save.upgrades[i]);});$$('[data-era]').forEach(b=>b.onclick=()=>{save.era=+b.dataset.era;persist();renderDrawer();toast(eras[save.era]+' chassis equipped');});$$('[data-cosmetic]').forEach(b=>b.onclick=()=>{save[b.dataset.cosmetic]=+b.dataset.index;persist();renderDrawer();});}
// A closed Catmull-Rom circuit; all racers use the same authored surface.
const controls=[[260,280],[560,190],[1020,190],[1470,260],[1540,440],[1300,540],[1140,450],[990,470],[1120,710],[1440,800],[1450,1000],[1110,1080],[740,1000],[660,820],[820,700],[680,570],[490,590],[420,890],[230,990],[120,790],[180,550]];
const path=[];for(let i=0;i<controls.length;i++){let a=controls[(i-1+controls.length)%controls.length],b=controls[i],c=controls[(i+1)%controls.length],d=controls[(i+2)%controls.length];for(let j=0;j<32;j++){let t=j/32;path.push({x:.5*((2*b[0])+(-a[0]+c[0])*t+(2*a[0]-5*b[0]+4*c[0]-d[0])*t*t+(-a[0]+3*b[0]-3*c[0]+d[0])*t*t*t),y:.5*((2*b[1])+(-a[1]+c[1])*t+(2*a[1]-5*b[1]+4*c[1]-d[1])*t*t+(-a[1]+3*b[1]-3*c[1]+d[1])*t*t*t)});}}
let length=0;path.forEach((p,i)=>{p.s=length;const q=path[(i+1)%path.length];p.a=Math.atan2(q.y-p.y,q.x-p.x);p.seg=Math.hypot(q.x-p.x,q.y-p.y);length+=p.seg;});
function at(s){s=((s%length)+length)%length;let lo=0,hi=path.length-1;while(lo<hi){let m=Math.ceil((lo+hi)/2);if(path[m].s>s)hi=m-1;else lo=m;}let p=path[lo],q=path[(lo+1)%path.length],t=(s-p.s)/p.seg;return{x:p.x+(q.x-p.x)*t,y:p.y+(q.y-p.y)*t,a:p.a,h:(p.h||0)+((q.h||0)-(p.h||0))*t,index:lo};}
function nearest(x,y,height=null){let best=Infinity,found;for(let i=0;i<path.length;i++){let p=path[i],q=path[(i+1)%path.length],dx=q.x-p.x,dy=q.y-p.y,t=Math.max(0,Math.min(1,((x-p.x)*dx+(y-p.y)*dy)/(dx*dx+dy*dy))),px=p.x+dx*t,py=p.y+dy*t,d=(x-px)**2+(y-py)**2;const h=(p.h||0)+((q.h||0)-(p.h||0))*t,score=d+(height===null?0:(h-height)**2*16);if(score<best){best=score;found={h,dist:Math.sqrt(d),s:p.s+t*p.seg,x:px,y:py,a:p.a};}}return found;}
const wrap=a=>Math.atan2(Math.sin(a),Math.cos(a));
const fmt=t=>Math.floor(t/60)+':'+(t%60).toFixed(2).padStart(5,'0');
let race=null,keys={},last=0,cam={x:850,y:630},frameCount=0;
const game=$('#game'),ctx=null;
function performanceStats(){const u=save.upgrades;return{max:265+u[2]*18+save.era*12,accel:112+u[2]*10+u[3]*22,brake:210+u[1]*65,steer:2.35+u[0]*.12+u[5]*.12,grip:.85+u[0]*.07+u[4]*.08,grass:85+u[5]*15};}
function startRace(){keys={};const p=at(-170);race={elapsed:0,count:3.2,paused:false,done:false,lapStart:0,best:null,completed:0,difficulty:$('#difficulty').value,player:{...p,speed:0,progress:-170,prevS:length-170,lap:0,gate:0},ai:Array.from({length:5},(_,i)=>({name:['V. Rossi','A. Silva','J. Park','M. Dubois','L. Weber'][i],progress:-i*29,speed:0,lane:i%2?18:-18,color:['#e0be4e','#f1eee1','#649bc0','#ce7b4d','#7774a8'][i]}))};$('#lobby').hidden=true;$('header').hidden=true;$('#raceView').hidden=false;$('#overlay').hidden=true;$('#countdown').textContent='3';cam={x:p.x,y:p.y};resize();window.scrollTo(0,0);}
$('#start').onclick=startRace;
function exitRace(){race=null;keys={};$('#raceView').hidden=true;$('#lobby').hidden=false;$('header').hidden=false;$('#overlay').hidden=true;setTab('race');if(gain)gain.gain.value=0;}
function pause(){if(!race||race.done)return;race.paused=!race.paused;keys={};$('#overlay').hidden=!race.paused;if(race.paused){$('#overlay').innerHTML='<div class="modal"><span class="eyebrow">TAKE A BREATHER</span><h2>In the pits.</h2><p>Your race is paused. Pick up right where you left off.</p><div class="buttons"><button class="primary" id="resume">Resume race</button><button id="restart">Restart</button><button id="quit">Exit</button></div></div>';$('#resume').onclick=pause;$('#restart').onclick=startRace;$('#quit').onclick=exitRace;$('#resume').focus();}}
$('#pause').onclick=pause;
function recover(){if(!race||race.done||race.paused)return;const p=race.player,point=at(p.progress);p.x=point.x;p.y=point.y;p.a=point.a;p.speed=0;p.prevS=((p.progress%length)+length)%length;toast('Back on track');}
window.addEventListener('keydown',e=>{if(race&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d','W','A','S','D','Escape','r','R'].includes(e.key)){e.preventDefault();if(e.key==='Escape'&&!e.repeat)pause();if(e.key.toLowerCase()==='r'&&!e.repeat)recover();keys[e.key.toLowerCase()]=true;}});window.addEventListener('keyup',e=>keys[e.key.toLowerCase()]=false);window.addEventListener('blur',()=>{keys={};if(race&&!race.paused&&!race.done)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&race&&!race.paused&&!race.done)pause();});
$$('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys[b.dataset.key.toLowerCase()]=true;};b.onpointerup=b.onpointercancel=()=>keys[b.dataset.key.toLowerCase()]=false;});
function finish(){if(race.done)return;race.done=true;const pos=1+race.ai.filter(a=>a.progress>length*3).length,reward=250+(6-pos)*75,xp=120+(pos===1?80:0),oldLevel=level();save.credits+=reward;save.xp+=xp;save.races++;if(pos===1)save.wins++;if(race.best&&(!save.bestLap||race.best<save.bestLap))save.bestLap=race.best;save.history.unshift({position:pos,time:race.elapsed,reward,circuit:window.race3D?.trackName||'Verdant Circuit'});save.history=save.history.slice(0,12);persist();$('#overlay').hidden=false;$('#overlay').innerHTML=`<div class="modal"><span class="eyebrow">CHEQUERED FLAG / ${window.race3D?.trackName||'VERDANT CIRCUIT'}</span><h2>${pos===1?'Top step.':'That’s a finish.'}</h2><p>Position <b>${pos} of 6</b> · ${fmt(race.elapsed)}<br>${level()>oldLevel?'Level up! '+eras[level()-1]+' chassis and new cosmetics unlocked.':'Every lap is a little more experience. Every finish is progress.'}</p><div class="result-stats"><span>◈ +${reward}</span><span>+${xp} XP</span><span>${race.best?fmt(race.best):'—'} best</span></div><div class="buttons"><button class="primary" id="again">Race again</button><button id="garageResult">Go to garage</button></div></div>`;$('#again').onclick=startRace;$('#garageResult').onclick=()=>{exitRace();setTab('car');};$('#garageResult').focus();}
function step(dt){if(!race||race.paused||race.done)return;if(race.count>0){race.count-=dt;$('#countdown').textContent=race.count>0?Math.ceil(race.count):'GO';return;}$('#countdown').textContent=race.elapsed<.8?'GO':'';race.elapsed+=dt;const p=race.player,stat=performanceStats(),n=nearest(p.x,p.y,at(p.progress).h),off=n.dist>49,gas=keys.arrowup||keys.w,brake=keys.arrowdown||keys.s||keys[' '],steer=(keys.arrowright||keys.d?1:0)-(keys.arrowleft||keys.a?1:0);
if(gas)p.speed+=stat.accel*dt;else p.speed-=35*dt;if(brake)p.speed-=stat.brake*dt;p.speed=Math.max(0,Math.min(p.speed,stat.max));if(off)p.speed=Math.max(0,p.speed-(p.speed>stat.grass?190:25)*dt);
const turnSpeed=stat.steer*(.35+.65*Math.min(p.speed/90,1))/(1+Math.max(0,p.speed-140)/(210*stat.grip));p.a+=steer*turnSpeed*dt*Math.min(p.speed/25,1);p.x+=Math.cos(p.a)*p.speed*dt;p.y+=Math.sin(p.a)*p.speed*dt;p.x=Math.max(25,Math.min(1640,p.x));p.y=Math.max(65,Math.min(1170,p.y));
let now=nearest(p.x,p.y,at(p.progress).h);if(now.dist>51){const dx=p.x-now.x,dy=p.y-now.y;p.x=now.x+dx/now.dist*51;p.y=now.y+dy/now.dist*51;p.speed*=Math.exp(-dt*4);now=nearest(p.x,p.y,at(p.progress).h);}let delta=now.s-p.prevS;if(delta<-length/2)delta+=length;if(delta>length/2)delta-=length;
// Credit only continuous movement along the course; cutting across the infield cannot advance checkpoints.
if(now.dist<65&&Math.abs(delta)<stat.max*dt*3+5){p.progress+=delta;}p.prevS=now.s;
const laps=Math.max(0,Math.floor(p.progress/length));if(laps>race.completed){const lt=race.elapsed-race.lapStart;race.best=race.best?Math.min(race.best,lt):lt;race.lapStart=race.elapsed;race.completed=laps;if(laps>=3){finish();return;}}
const base={easy:150,normal:181,hard:207}[race.difficulty];race.ai.forEach((a,i)=>{const point=at(a.progress),ahead=at(a.progress+65),bend=Math.abs(wrap(ahead.a-point.a)),target=(base+i*3)*(1-Math.min(.50,bend*.58));a.speed+=(target-a.speed)*Math.min(1,dt*1.4);a.progress+=a.speed*dt;const q=at(a.progress);a.x=q.x-Math.sin(q.a)*a.lane;a.y=q.y+Math.cos(q.a)*a.lane;a.a=q.a;if(Math.abs(at(a.progress).h-at(p.progress).h)<15&&Math.hypot(a.x-p.x,a.y-p.y)<22){p.speed*=Math.pow(.60,dt);const dx=p.x-a.x,dy=p.y-a.y,d=Math.hypot(dx,dy)||1;p.x+=dx/d*24*dt;p.y+=dy/d*24*dt;}});
if(frameCount%6===0){$('#position').innerHTML=(1+race.ai.filter(a=>a.progress>p.progress).length)+' <em>/ 6</em>';$('#lap').innerHTML=Math.min(3,race.completed+1)+' <em>/ 3</em>';$('#time').textContent=fmt(race.elapsed);$('#speed').textContent=Math.round(p.speed*.72);$('#speedbar').style.width=p.speed/stat.max*100+'%';const sorted=[...race.ai,{name:'YOU',progress:p.progress,you:true}].sort((a,b)=>b.progress-a.progress);$('#leaderboard').innerHTML=sorted.map((a,i)=>`<div class="leader-row ${a.you?'you':''}"><span>${i+1}</span><span>${a.name}</span></div>`).join('');$('#raceHint').textContent=off?'OFF TRACK · Return to the asphalt · R to recover':Math.cos(p.a-now.a)<-.4?'WRONG WAY · Turn around to continue your lap':'WASD / Arrows to drive · Space to brake · R to recover';}
if(osc&&gain){osc.frequency.value=45+p.speed*.65;gain.gain.value=sound?.025:0;}}
// Deterministic scenery stays stable between races.
let seed=42;const rand=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};const trees=[];for(let i=0;i<450;i++){let x=rand()*1740-30,y=rand()*1200;if(nearest(x,y).dist>95)trees.push({x,y,r:9+rand()*13,c:rand()>.5?'#4d754d':'#628750'});}
function line(c,width,color,dash=[]){c.beginPath();path.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.lineWidth=width;c.strokeStyle=color;c.setLineDash(dash);c.stroke();c.setLineDash([]);}
function drawTrack(c){c.fillStyle='#91a979';c.fillRect(-200,-200,2200,1600);c.fillStyle='#849f6e';for(let i=0;i<12;i++){c.fillRect(-200,i*115,2200,50);}c.fillStyle='#779d96';c.beginPath();c.ellipse(870,860,93,45,-.2,0,Math.PI*2);c.fill();c.strokeStyle='#c1caac';c.lineWidth=10;c.stroke();line(c,133,'#68865c');line(c,117,'#e2e6d4');line(c,113,'#cc6350',[20,20]);line(c,98,'#4c5754');line(c,87,'#555f5a');line(c,1,'#afb4a155',[12,26]);
// Start / finish gantry and checkers.
const start=at(0);c.save();c.translate(start.x,start.y);c.rotate(start.a);for(let x=0;x<3;x++)for(let y=0;y<10;y++){c.fillStyle=(x+y)%2?'#f0f0df':'#263630';c.fillRect(x*7-7,y*9-45,7,9);}c.restore();
for(const t of trees){c.fillStyle='#233d3326';c.beginPath();c.ellipse(t.x+6,t.y+7,t.r,t.r*.65,0,0,Math.PI*2);c.fill();c.fillStyle=t.c;c.beginPath();c.arc(t.x,t.y,t.r,0,Math.PI*2);c.fill();c.fillStyle='#a1bb7535';c.beginPath();c.arc(t.x-4,t.y-4,t.r*.6,0,Math.PI*2);c.fill();}
// Pit buildings and grandstands.
c.save();c.translate(780,90);c.fillStyle='#364c4130';c.fillRect(8,8,280,50);c.fillStyle='#dce1cd';c.fillRect(0,0,280,50);c.fillStyle='#65756b';for(let i=0;i<10;i++)c.fillRect(i*28+3,8,20,28);c.fillStyle='#e7edce';c.font='bold 17px Arial';c.fillText('POCKET MOTORSPORT',32,-12);c.restore();c.save();c.translate(1550,600);c.rotate(Math.PI/2);c.fillStyle='#c1c9b0';c.fillRect(0,0,240,45);for(let r=0;r<4;r++)for(let i=0;i<30;i++){c.fillStyle=['#d57351','#b5c6a0','#ede9c7'][i%3];c.fillRect(i*8+1,r*11+2,5,6);}c.restore();}
const trackCanvas=document.createElement('canvas');trackCanvas.width=1800;trackCanvas.height=1300;drawTrack(trackCanvas.getContext('2d'));
function drawCar(c,x,y,a,color,era,helmet,suit,player=false){c.save();c.translate(x,y);c.rotate(a);c.fillStyle='#182d2735';c.fillRect(-17,-11,39,26);c.fillStyle='#162522';for(let v of [-1,1]){c.fillRect(-13,v*10-4,12,8);c.fillRect(9,v*10-4,11,8);}c.fillStyle=player&&save.upgrades[0]>0?'#dfff60':'#97a48c';for(let v of [-1,1]){c.fillRect(-9,v*13-1,5,2);c.fillRect(12,v*13-1,5,2);}c.fillStyle=color;c.beginPath();c.moveTo(23+era*2,-3);c.lineTo(3,-6);c.lineTo(-6,-9);c.lineTo(-15,-7);c.lineTo(-15,7);c.lineTo(-6,9);c.lineTo(3,6);c.lineTo(23+era*2,3);c.closePath();c.fill();c.fillRect(-17,-15,5+era,30);c.fillStyle=era>0?'#e6e9d9':color;c.fillRect(18,-14-era,4,28+era*2);c.fillStyle=suit;c.fillRect(-6,-5,9,10);c.fillStyle='#20302d';c.beginPath();c.ellipse(0,0,7,5,0,0,Math.PI*2);c.fill();c.fillStyle=helmet;c.beginPath();c.arc(-1,0,4.8,0,Math.PI*2);c.fill();c.fillStyle='#30453f';c.fillRect(1,-4,2,8);if(era===2){c.strokeStyle='#1a2827';c.lineWidth=2;c.beginPath();c.ellipse(1,0,9,6,0,0,Math.PI*2);c.stroke();}c.fillStyle='#eef0db';c.fillRect(9,-1,8,2);c.restore();if(player){c.fillStyle='#fff';c.beginPath();c.moveTo(x,y-28);c.lineTo(x-5,y-35);c.lineTo(x+5,y-35);c.fill();}}
function resize(){if(window.race3D){window.race3D.renderer.setSize(innerWidth,innerHeight);return;}const d=Math.min(devicePixelRatio||1,2);game.width=Math.round(innerWidth*d);game.height=Math.round(innerHeight*d);game.style.width=innerWidth+'px';game.style.height=innerHeight+'px';}window.addEventListener('resize',resize);
function render(dt){if(!race)return;const w=innerWidth,h=innerHeight,d=Math.min(devicePixelRatio||1,2),p=race.player,zoom=w<760?.8:Math.max(.65,Math.min(1.0,w/1550));const k=matchMedia('(prefers-reduced-motion: reduce)').matches?1:1-Math.exp(-dt*5);cam.x+=(p.x+Math.cos(p.a)*90-cam.x)*k;cam.y+=(p.y+Math.sin(p.a)*90-cam.y)*k;ctx.setTransform(d,0,0,d,0,0);ctx.fillStyle='#91a979';ctx.fillRect(0,0,w,h);const cx=Math.max(w/(2*zoom),Math.min(1800-w/(2*zoom),cam.x)),cy=Math.max(h*.55/zoom,Math.min(1300-h*.45/zoom,cam.y));ctx.translate(w/2,h*.55);ctx.scale(zoom,zoom);ctx.translate(-cx,-cy);ctx.drawImage(trackCanvas,0,0);race.ai.forEach(a=>{const q=a.x===undefined?at(a.progress):a;drawCar(ctx,q.x,q.y,q.a,a.color,1,'#d9e3cb',a.color);});drawCar(ctx,p.x,p.y,p.a,colors[save.color][1],save.era,helmets[save.helmet][1],suits[save.suit][1],true);
// Live minimap uses world positions rather than a decorative image.
ctx.setTransform(d,0,0,d,0,0);const mw=w<760?120:190,mh=mw*.72,mx=w-mw-25,my=105;ctx.fillStyle='#20352bdd';ctx.fillRect(mx,my,mw,mh);ctx.save();ctx.translate(mx+8,my+4);ctx.scale((mw-16)/1700,(mh-8)/1200);line(ctx,26,'#8c9e80');race.ai.forEach(a=>{const q=at(a.progress);ctx.fillStyle=a.color;ctx.beginPath();ctx.arc(q.x,q.y,20,0,Math.PI*2);ctx.fill();});ctx.fillStyle='#dfff60';ctx.beginPath();ctx.arc(p.x,p.y,27,0,Math.PI*2);ctx.fill();ctx.restore();}
function loop(now){const dt=Math.min(.04,(now-last)/1000||.016);last=now;frameCount++;step(dt);window.race3D?.render(dt,race);if(race&&(race.paused||race.done)&&gain)gain.gain.value=0;requestAnimationFrame(loop);}requestAnimationFrame(loop);
function preview(){const c=$('#preview').getContext('2d');c.clearRect(0,0,540,310);c.save();c.translate(60,0);c.scale(.25,.25);line(c,50,'#344d3d');line(c,20,'#bed49d');const p=at(0);c.fillStyle='#dfff60';c.beginPath();c.arc(p.x,p.y,26,0,Math.PI*2);c.fill();c.restore();}
$('#sound').onclick=()=>{sound=!sound;if(sound&&!audio){audio=new (window.AudioContext||window.webkitAudioContext)();osc=audio.createOscillator();gain=audio.createGain();osc.type='sawtooth';gain.gain.value=0;osc.connect(gain);gain.connect(audio.destination);osc.start();}if(audio)audio.resume();$('#sound').textContent=sound?'Sound on':'Sound off';if(gain&&!sound)gain.gain.value=0;};
updateProfile();preview();
window.PocketGP={get race(){return race;},get save(){return save;},get keys(){return keys;},at,get length(){return length;},nearest,step,startRace,performanceStats,get path(){return path;},setCircuit(points){path.length=0;for(let i=0;i<points.length;i++){const a=points[(i-1+points.length)%points.length],b=points[i],c=points[(i+1)%points.length],d=points[(i+2)%points.length];for(let j=0;j<32;j++){const t=j/32;const v=k=>.5*(2*b[k]+(-a[k]+c[k])*t+(2*a[k]-5*b[k]+4*c[k]-d[k])*t*t+(-a[k]+3*b[k]-3*c[k]+d[k])*t*t*t);path.push({x:v(0),y:v(1),h:v(2)});}}length=0;path.forEach((p,i)=>{const q=path[(i+1)%path.length];p.s=length;p.a=Math.atan2(q.y-p.y,q.x-p.x);p.seg=Math.hypot(q.x-p.x,q.y-p.y);length+=p.seg;});preview();}};
