import * as THREE from 'three';
import {GLTFLoader} from './public/vendor/jsm/loaders/GLTFLoader.js';
import {mergeGeometries} from './public/vendor/jsm/utils/BufferGeometryUtils.js';
import {RoomEnvironment} from './public/vendor/jsm/environments/RoomEnvironment.js';
import {EffectComposer} from './public/vendor/jsm/postprocessing/EffectComposer.js';
import {RenderPass} from './public/vendor/jsm/postprocessing/RenderPass.js';
import {UnrealBloomPass} from './public/vendor/jsm/postprocessing/UnrealBloomPass.js';
import {OutputPass} from './public/vendor/jsm/postprocessing/OutputPass.js';
import {RoundedBoxGeometry} from './public/vendor/jsm/geometries/RoundedBoxGeometry.js';

const gp=window.PocketGP, $=s=>document.querySelector(s), S=.1;
const tracks=[
 {name:'Verdant Grand Prix',tag:'01 / FOREST · DAYLIGHT',note:'Tree-lined bends, grandstands and rolling hills.',night:false,points:[[260,280,0],[560,190,0],[1020,190,0],[1470,260,12],[1540,440,28],[1300,540,42],[1140,450,36],[990,470,20],[1120,710,0],[1440,800,0],[1450,1000,0],[1110,1080,18],[740,1000,32],[660,820,26],[820,700,10],[680,570,0],[490,590,0],[420,890,0],[230,990,0],[120,790,0],[180,550,0]]},
 {name:'Neon Harbor',tag:'02 / WATERFRONT · NIGHT',note:'Cyan edge lights, a glowing skyline and harbor ramps.',night:true,points:[[260,270,0],[650,180,0],[1220,180,0],[1480,300,10],[1480,540,35],[1210,640,60],[1060,480,65],[810,430,50],[730,680,25],[1000,820,0],[1410,860,0],[1440,1070,0],[970,1080,0],[610,920,12],[430,1060,20],[160,960,0],[180,660,0],[420,520,0]]},
 {name:'Skyline Overpass',tag:'03 / STACKED DECKS · DUSK',note:'A true figure-eight: climb above rivals, then race underneath.',night:true,points:[[250,300,0],[560,310,35],[850,590,125],[1170,900,125],[1460,940,100],[1540,720,30],[1430,360,0],[1210,270,0],[1030,420,0],[850,590,0],[570,860,0],[270,980,0],[140,760,0],[150,470,0]]}
];
let selected=0,mode='cockpit',activeRace=null,loaded=0,failed=false;
const renderer=new THREE.WebGLRenderer({canvas:$('#game'),antialias:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
renderer.localClippingEnabled=true;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(78,innerWidth/innerHeight,.06,420);
const pmrem=new THREE.PMREMGenerator(renderer),studio=new RoomEnvironment();scene.environment=pmrem.fromScene(studio,.04).texture;studio.dispose();pmrem.dispose();scene.environmentIntensity=.7;
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));const bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.32,.5,1.25);composer.addPass(bloom);composer.addPass(new OutputPass());
let world=new THREE.Group();scene.add(world);
const hemi=new THREE.HemisphereLight(0xc8e7ff,0x445536,2.3);scene.add(hemi);
const sun=new THREE.DirectionalLight(0xfff0d6,3.2);sun.position.set(80,110,-30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-110,right:110,top:100,bottom:-100,near:1,far:300});sun.shadow.bias=-.0005;sun.target.position.set(85,0,60);scene.add(sun,sun.target);
const mat=(color,roughness=.7,metalness=0,emissive=0)=>new THREE.MeshStandardMaterial({color,roughness,metalness,emissive,emissiveIntensity:emissive?2.8:0});
const mats={road:mat(0x343a40,.92),edge:mat(0xe9e7dc),red:mat(0xc92527),grass:mat(0x526446),concrete:mat(0x59616b),steel:mat(0x687680,.35,.7),dark:mat(0x131c24),leaf:mat(0x315f39),leaf2:mat(0x557a43),bark:mat(0x514438),blue:mat(0x1fa8ca),glass:mat(0x243d55,.22,.65),glow:mat(0x70efff,.25,.2,0x22bddd),pink:mat(0xff4b7b,.3,.2,0xd92768),yellow:mat(0xe5c951),white:mat(0xe2e5e5),seat:mat(0xc12c35),car:mat(0xc71c28,.28,.45),rubber:mat(0x141517,.85),carbon:mat(0x14191f,.35,.3)};
const asphalt=document.createElement('canvas');asphalt.width=asphalt.height=256;const ac=asphalt.getContext('2d'),pixels=ac.createImageData(256,256);let noise=42;for(let i=0;i<pixels.data.length;i+=4){noise=(noise*1664525+1013904223)>>>0;const v=110+(noise%65);pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=v;pixels.data[i+3]=255;}ac.putImageData(pixels,0,0);const asphaltTex=new THREE.CanvasTexture(asphalt);asphaltTex.wrapS=asphaltTex.wrapT=THREE.RepeatWrapping;asphaltTex.repeat.set(4,2);mats.road.map=asphaltTex;mats.road.bumpMap=asphaltTex;mats.road.bumpScale=.025;mats.road.color.set(0x3d4349);mats.concrete.side=THREE.DoubleSide;
const batches=new Map();
function shape(geo,m,x,y,z,ry=0){if(geo.index){const original=geo;geo=geo.toNonIndexed();original.dispose();}geo.rotateY(ry);geo.translate(x,y,z);if(!batches.has(m))batches.set(m,[]);batches.get(m).push(geo);}
const box=(x,y,z,w,h,d,m,ry=0)=>shape(new THREE.BoxGeometry(w,h,d),m,x,y,z,ry);
function flush(){for(const [material,geos]of batches){const g=mergeGeometries(geos,false);const mesh=new THREE.Mesh(g,material);mesh.castShadow=material!==mats.glow;mesh.receiveShadow=true;world.add(mesh);geos.forEach(g=>g.dispose());}batches.clear();}
function strip(offset,width,lift,material){const positions=[],uv=[],indices=[],path=gp.path;for(let i=0;i<=path.length;i++){const p=path[i%path.length],nx=-Math.sin(p.a),nz=Math.cos(p.a);for(const side of [-1,1]){const lateral=offset+side*width/2;positions.push(p.x*S+nx*lateral,(p.h||0)*S+lift,p.y*S+nz*lateral);uv.push(side===1?1:0,i*.5);}if(i<path.length){const k=i*2;indices.push(k,k+1,k+2,k+1,k+3,k+2);}}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();const mesh=new THREE.Mesh(g,material);mesh.receiveShadow=true;world.add(mesh);}
function sign(text,x,y,z,angle=0,width=12){const c=document.createElement('canvas');c.width=1024;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#101c27';ctx.fillRect(0,0,1024,128);ctx.fillStyle='#9df6e9';ctx.font='bold 56px sans-serif';ctx.textAlign='center';ctx.fillText(text,512,83);const t=new THREE.CanvasTexture(c),m=new THREE.MeshBasicMaterial({map:t,side:THREE.DoubleSide});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(width,width/8),m);mesh.position.set(x,y,z);mesh.rotation.y=angle;world.add(mesh);}
let seed=1;function random(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
function buildTrack(){scene.remove(world);world.traverse(o=>{o.geometry?.dispose();if(o.material?.map&&o.material!==mats.road){o.material.map.dispose();o.material.dispose();}});world=new THREE.Group();scene.add(world);const t=tracks[selected];gp.setCircuit(t.points);seed=26;
 scene.background=new THREE.Color(t.night?selected===2?0x152039:0x040d1b:0xa4c6d9);scene.fog=new THREE.Fog(scene.background,100,290);hemi.intensity=t.night?1.15:2.3;sun.intensity=t.night?.6:3.2;sun.color.set(t.night?0x889dff:0xfff0d6);
 box(85,-.9,63,500,1,400,t.night?mats.dark:mats.grass);
 scene.environmentIntensity=t.night?.6:.85;bloom.strength=t.night?.5:.12;
 strip(0,11.6,-.24,mats.concrete);strip(0,9.8,.02,mats.road);strip(-4.5,.11,.04,mats.white);strip(4.5,.11,.04,mats.white);strip(-5.9,.18,.85,mats.steel);strip(5.9,.18,.85,mats.steel);if(t.night){strip(-5.8,.12,.97,mats.glow);strip(5.8,.12,.97,mats.pink);}
 const path=gp.path;
 if(selected===1){const water=new THREE.Mesh(new THREE.PlaneGeometry(300,70),mat(0x164e68,.2,.55));water.rotation.x=-Math.PI/2;water.position.set(85,-.33,152);world.add(water);for(let i=0;i<8;i++){const x=15+i*23;box(x,12,132,.6,24,.6,mats.yellow);box(x+6,23,132,19,.45,.45,mats.yellow);box(x+13,16,132,.06,14,.06,mats.steel);box(x,1.2,128,10,2.4,4,mats.concrete);}}
 if(!t.night){for(let i=0;i<22;i++){const x=-80+i*16,z=145+random()*40,h=12+random()*24;shape(new THREE.ConeGeometry(15+random()*12,h,7),mats.leaf2,x,h/2-1,z);}for(let i=0;i<14;i++){const x=random()*240-30,z=random()*130;shape(new THREE.SphereGeometry(7,8,5),mats.white,x,45+random()*12,z);}}
 for(let i=0;i<path.length;i+=3){const p=path[i],x=p.x*S,z=p.y*S,y=(p.h||0)*S,angle=-p.a;
  for(const side of [-1,1]){const nx=-Math.sin(p.a)*side,nz=Math.cos(p.a)*side;box(x+nx*5.1,y+.07,z+nz*5.1,1.2,.14,.6,i%6?mats.white:mats.red,angle);box(x+nx*6,y+.6,z+nz*6,1.4,.7,.16,mats.steel,angle);if(t.night)box(x+nx*5.85,y+.98,z+nz*5.85,1.6,.09,.09,side>0?mats.glow:mats.pink,angle);}
  if(i%15===0){for(const side of [-1,1]){const nx=-Math.sin(p.a)*side,nz=Math.cos(p.a)*side;box(x+nx*6,y+.7,z+nz*6,.18,1.4,.18,mats.steel);if(y>1)box(x+nx*4,-.4+y/2,z+nz*4,.9,y+.8,.9,mats.concrete);}}
  if(i%36===0){const nx=-Math.sin(p.a),nz=Math.cos(p.a);box(x+nx*7,y+3.5,z+nz*7,.18,7,.18,mats.steel);box(x+nx*6.2,y+7,z+nz*6.2,2,.12,.5,t.night?mats.glow:mats.white,angle);}
 }
 // Paddock buildings, pit garages and a populated grandstand alongside the straight.
 for(let i=0;i<10;i++){box(48+i*7,2.1,7,6.6,4.2,7,mats.concrete);box(48+i*7,1.6,10.55,5.5,2.9,.1,mats.dark);box(48+i*7,4.8,7,6.6,1.4,7,mats.glass);box(48+i*7,5.6,7,6.9,.2,7.3,mats.white);}
 sign('POCKET MOTORSPORT  /  PIT LANE',78,4,10.7,0,31);
 for(let row=0;row<5;row++){box(85,1+row*.65,29+row*1.15,55,.4,1.1,mats.concrete);for(let j=0;j<75;j++){box(58+j*.72,1.45+row*.65,29+row*1.15,.38,.5,.4,[mats.seat,mats.white,mats.blue][j%3]);}}
 box(85,6.2,31,59,.2,8,mats.steel);for(let x=57;x<115;x+=14)box(x,3,34,.25,6,.25,mats.steel);
 // Trees or illuminated towers, kept clear of every part of the racing surface.
 for(let i=0;i<330;i++){const x=random()*190-10,z=random()*140-8;if(gp.nearest(x/S,z/S).dist<105)continue;if(!t.night){const h=3+random()*5;shape(new THREE.CylinderGeometry(.18,.3,h,5),mats.bark,x,h/2,z);shape(new THREE.IcosahedronGeometry(h*.48,1),i%2?mats.leaf:mats.leaf2,x,h,z);}else if(i%3===0){const h=4+random()*24,w=2+random()*5;box(x,h/2,z,w,h,w,mats.glass);for(let r=2;r<h;r+=2.5)box(x,r,z+w/2+.01,w*.82,.12,.04,i%2?mats.glow:mats.pink);}}
 // Grid marks and start gantry aligned to the circuit tangent.
 const p=gp.at(0),nx=-Math.sin(p.a),nz=Math.cos(p.a);for(let j=-5;j<5;j++)box(p.x*S+nx*j,.06,p.y*S+nz*j,.7,.03,.7,j%2?mats.white:mats.dark,-p.a);
 for(const side of [-1,1])box(p.x*S+nx*6.5*side,3,p.y*S+nz*6.5*side,.3,6,.3,mats.steel);
 box(p.x*S,6,p.y*S,.4,.5,14,mats.steel,-p.a);sign(t.name.toUpperCase(),p.x*S,5.7,p.y*S,-p.a-Math.PI/2,11);
 flush();$('#track-name').textContent=t.name;$('.track-title h2').textContent=t.name;$('.circuit-label').textContent=t.tag;$('.track-preview p').textContent=t.note;
}
// Physical driver cockpit: steering, gloves, front tires and halo, rendered in world space.
const driver=new THREE.Group();scene.add(driver);
const cockpitClip=new THREE.Plane();let importedCockpit;
function mesh(parent,geo,material,x=0,y=0,z=0){if(geo.type==='BoxGeometry'){const p=geo.parameters;geo.dispose();geo=new RoundedBoxGeometry(p.width,p.height,p.depth,3,Math.min(p.width,p.height,p.depth)*.22);}const m=new THREE.Mesh(geo,material);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function bar(parent,a,b,r,material){const av=new THREE.Vector3(...a),bv=new THREE.Vector3(...b),d=bv.clone().sub(av);const m=mesh(parent,new THREE.CylinderGeometry(r,r,d.length(),8),material,...av.clone().add(bv).multiplyScalar(.5).toArray());m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return m;}
const noseShape=new THREE.Shape();noseShape.moveTo(-.38,.0);noseShape.lineTo(.38,0);noseShape.lineTo(.16,-2.25);noseShape.quadraticCurveTo(0,-2.43,-.16,-2.25);noseShape.closePath();const noseGeo=new THREE.ExtrudeGeometry(noseShape,{depth:.22,bevelEnabled:true,bevelSize:.045,bevelThickness:.04,bevelSegments:3,steps:1});noseGeo.rotateX(Math.PI/2);mesh(driver,noseGeo,mats.car,0,.49,-.25);
for(const s of [-1,1]){mesh(driver,new THREE.BoxGeometry(.25,.5,1.45),mats.car,s*.52,.45,.0);const wheel=mesh(driver,new THREE.CylinderGeometry(.36,.36,.32,24),mats.rubber,s*.91,.36,-1.65);wheel.rotation.z=Math.PI/2;for(const y of [.2,.43])bar(driver,[s*.2,y,-1],[s*.85,y,-1.65],.025,mats.carbon);mesh(driver,new THREE.BoxGeometry(.25,.14,.18),mats.car,s*.72,.74,-.52);bar(driver,[s*.48,.48,-.4],[s*.71,.73,-.52],.035,mats.carbon);}
mesh(driver,new THREE.BoxGeometry(1.7,.08,.28),mats.car,0,.18,-2.32);
const halo=new THREE.Group();driver.add(halo);bar(halo,[-.57,1.21,.25],[-.57,1.21,-.77],.045,mats.carbon);bar(halo,[.57,1.21,.25],[.57,1.21,-.77],.045,mats.carbon);bar(halo,[-.57,1.21,-.77],[.57,1.21,-.77],.045,mats.carbon);bar(halo,[0,1.21,-.77],[0,.53,-1.1],.045,mats.carbon);
const proceduralExterior=[...driver.children].filter(o=>o!==halo);
const wheelRig=new THREE.Group();wheelRig.position.set(0,.57,-.34);driver.add(wheelRig);mesh(wheelRig,new THREE.BoxGeometry(.56,.31,.08),mats.carbon);for(const s of [-1,1]){mesh(wheelRig,new THREE.CapsuleGeometry(.06,.21,4,10),mats.rubber,s*.29,0,0);mesh(wheelRig,new THREE.CapsuleGeometry(.067,.13,4,10),mats.seat,s*.32,-.02,.045);bar(driver,[s*.33,.5,-.24],[s*.47,.22,.25],.08,mats.seat);}
wheelRig.position.z=-.48;wheelRig.scale.setScalar(.85);halo.position.y=.18;
const dash=document.createElement('canvas');dash.width=256;dash.height=128;const dc=dash.getContext('2d'),dashTex=new THREE.CanvasTexture(dash);mesh(wheelRig,new THREE.PlaneGeometry(.26,.13),new THREE.MeshBasicMaterial({map:dashTex}),0,.025,.046);
for(let i=0;i<8;i++)mesh(wheelRig,new THREE.SphereGeometry(.012,8,5),i<4?mats.glow:mats.pink,(i-3.5)*.035,.12,.046);
for(const s of [-1,1])for(let i=0;i<3;i++)mesh(wheelRig,new THREE.SphereGeometry(.025,8,5),[mats.red,mats.blue,mats.yellow][i],s*.21,-.09+i*.075,.047);
const carRoots=Array.from({length:6},()=>{const g=new THREE.Group();scene.add(g);return g;});
const templates={};
// A live transparent garage view uses the same imported car that enters the race.
const garageCanvas=document.createElement('canvas');garageCanvas.id='garage-model';$('.garage').append(garageCanvas);const garageRenderer=new THREE.WebGLRenderer({canvas:garageCanvas,alpha:true,antialias:true});garageRenderer.setPixelRatio(Math.min(devicePixelRatio,1.5));garageRenderer.setClearColor(0,0);garageRenderer.toneMapping=THREE.ACESFilmicToneMapping;const garageScene=new THREE.Scene();garageScene.environment=scene.environment;garageScene.environmentIntensity=1;const garageCamera=new THREE.PerspectiveCamera(34,1,.1,50);garageCamera.position.set(5,3.2,6.5);garageCamera.lookAt(0,.45,0);garageScene.add(new THREE.HemisphereLight(0xffffff,0x555555,2));const garageLight=new THREE.DirectionalLight(0xffffff,3);garageLight.position.set(4,6,5);garageScene.add(garageLight);let garageModel;
function updateGarage(){if(garageModel)garageScene.remove(garageModel);const template=templates[$('#car-model').value];if(template){garageModel=template.clone(true);garageScene.add(garageModel);$('#heroCar').style.visibility='hidden';$('#carname').textContent=$('#car-model').value==='2022'?'Modern · Red / black':'Heritage · Red / white';$('#liveryName').textContent='Imported race livery';}const rect=$('.garage').getBoundingClientRect();garageRenderer.setSize(rect.width,rect.height);garageCamera.aspect=rect.width/rect.height;garageCamera.updateProjectionMatrix();}
let garageLast=0;function animateGarage(now){requestAnimationFrame(animateGarage);if(!garageModel||!$('#raceView').hidden||now-garageLast<45)return;garageLast=now;garageModel.rotation.y=Math.sin(now*.00015)*.16;garageRenderer.render(garageScene,garageCamera);}requestAnimationFrame(animateGarage);
async function loadCars(){const loader=new GLTFLoader();await Promise.all(['2005','2022'].map(async era=>{try{const gltf=await loader.loadAsync(`public/models/ferrari-${era}-editable.glb`);const root=new THREE.Group(),model=gltf.scene;root.add(model);const bounds=new THREE.Box3().setFromObject(model),center=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3());model.position.sub(center);model.position.y+=size.y/2;root.scale.setScalar(4.7/size.x);root.rotation.y=Math.PI/2;root.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;if(o.material){o.material.metalness=Math.min(o.material.metalness||0,.45);o.material.roughness=Math.max(o.material.roughness||0,.32);}}});templates[era]=root;loaded++;}catch(error){console.error('Car asset failed',error);failed=true;}}));$('#start').disabled=failed;$('#start').innerHTML=failed?'Car loading failed — reload':'Start race <span>↗</span>';$('#asset-status').textContent=failed?'Could not load cars. Reload the game.':'2 imported GLB cars · Ready to drive';updateGarage();}
function assignCars(){carRoots.forEach((root,i)=>{root.clear();const era=i===0?$('#car-model').value:i%2?'2005':'2022';if(templates[era])root.add(templates[era].clone(true));});if(importedCockpit){driver.remove(importedCockpit);importedCockpit.traverse(o=>{if(o.isMesh)o.material.dispose();});}importedCockpit=templates[$('#car-model').value].clone(true);importedCockpit.traverse(o=>{if(o.isMesh){o.material=o.material.clone();o.material.clippingPlanes=[cockpitClip];o.material.clipShadows=true;}});driver.add(importedCockpit);proceduralExterior.forEach(o=>o.visible=false);}
const extra=document.createElement('div');extra.className='world-options';extra.innerHTML=`<label for="circuit">Circuit</label><select id="circuit">${tracks.map((t,i)=>`<option value="${i}">${t.name}</option>`).join('')}</select><label for="car-model">Race car</label><select id="car-model"><option value="2022">Modern · Red / black GLB</option><option value="2005">Heritage · Red / white GLB</option></select><small id="asset-status">Loading your 3D cars…</small>`;$('.race-options').prepend(extra);
const cameraButton=document.createElement('button');cameraButton.id='camera-mode';cameraButton.textContent='Cockpit · C';cameraButton.onclick=()=>{mode=mode==='cockpit'?'chase':'cockpit';cameraButton.textContent=mode==='cockpit'?'Cockpit · C':'Chase · C';};$('.race-top').append(cameraButton);
const trackLabel=document.createElement('div');trackLabel.id='track-name';$('#raceView').append(trackLabel);
$('#car-model').onchange=updateGarage;
$('#circuit').onchange=()=>{selected=Number($('#circuit').value);buildTrack();};
window.addEventListener('keydown',e=>{if(gp.race&&e.key.toLowerCase()==='c'&&!e.repeat)cameraButton.click();});
window.addEventListener('resize',()=>{renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);updateGarage();camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();});
$('#start').disabled=true;$('#start').textContent='Loading cars…';
let ticks=0;
const minimap=document.createElement('canvas');minimap.id='race-map';minimap.width=220;minimap.height=155;$('#raceView').append(minimap);const mc=minimap.getContext('2d');
const sparkCount=70,sparkPositions=new Float32Array(sparkCount*3),sparkLife=new Float32Array(sparkCount);sparkPositions.fill(-1000);const sparkGeo=new THREE.BufferGeometry();sparkGeo.setAttribute('position',new THREE.BufferAttribute(sparkPositions,3));const sparks=new THREE.Points(sparkGeo,new THREE.PointsMaterial({color:0xffc16b,size:.07,transparent:true,opacity:.8,depthWrite:false,blending:THREE.AdditiveBlending}));scene.add(sparks);let sparkIndex=0;
function drawMap(race){mc.clearRect(0,0,220,155);mc.fillStyle='#081722b8';mc.fillRect(0,0,220,155);mc.save();mc.translate(7,7);mc.scale(.12,.12);mc.beginPath();gp.path.forEach((p,i)=>i?mc.lineTo(p.x,p.y):mc.moveTo(p.x,p.y));mc.closePath();mc.strokeStyle='#658890';mc.lineWidth=19;mc.stroke();race.ai.forEach(a=>{const p=gp.at(a.progress);mc.fillStyle='#e8e8df';mc.beginPath();mc.arc(p.x,p.y,15,0,7);mc.fill();});mc.fillStyle='#dfff60';mc.beginPath();mc.arc(race.player.x,race.player.y,22,0,7);mc.fill();mc.restore();mc.fillStyle='#a5dfdf';mc.font='10px monospace';mc.fillText(`DECK ${gp.at(race.player.progress).h>70?'UPPER':'LOWER'}`,12,145);}
window.race3D={get trackName(){return tracks[selected].name;},get mode(){return mode;},get loaded(){return loaded;},get tracks(){return tracks;},get renderer(){return renderer;},render(dt,race){if(!race)return;if(activeRace!==race){activeRace=race;assignCars();}const p=race.player,point=gp.at(p.progress),ahead=gp.at(p.progress+12),pitch=Math.atan2((ahead.h-point.h)*S,1.2),heading=-p.a-Math.PI/2;
 const rig=carRoots[0];rig.position.set(p.x*S,point.h*S+.08,p.y*S);rig.rotation.set(0,heading,0);rig.rotateX(pitch);rig.visible=mode==='chase';driver.visible=mode==='cockpit';driver.position.copy(rig.position);driver.quaternion.copy(rig.quaternion);halo.visible=$('#car-model').value==='2022';
 race.ai.forEach((ai,i)=>{const a=gp.at(ai.progress),next=gp.at(ai.progress+12),r=carRoots[i+1];r.position.set((a.x-Math.sin(a.a)*ai.lane)*S,a.h*S+.08,(a.y+Math.cos(a.a)*ai.lane)*S);r.rotation.set(0,-a.a-Math.PI/2,0);r.rotateX(Math.atan2((next.h-a.h)*S,1.2));});
 const steering=(gp.keys.arrowright||gp.keys.d?1:0)-(gp.keys.arrowleft||gp.keys.a?1:0);wheelRig.rotation.z=THREE.MathUtils.damp(wheelRig.rotation.z,-steering*.38,9,dt);
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,bob=reduced||race.paused?0:Math.sin(race.elapsed*32)*Math.min(p.speed/260,1)*.006;
 const eye=new THREE.Vector3(0,mode==='cockpit'?.98+bob:3.1,mode==='cockpit'?.27:6.4).applyQuaternion(rig.quaternion).add(rig.position),look=new THREE.Vector3(0,mode==='cockpit'?.89:1,-12).applyQuaternion(rig.quaternion).add(rig.position);camera.position.copy(eye);camera.up.set(0,1,0);camera.lookAt(look);camera.fov=(innerWidth<700?88:78)+(reduced?0:p.speed/265*5);camera.updateProjectionMatrix();
 if(ticks++%8===0){dc.fillStyle='#04111b';dc.fillRect(0,0,256,128);dc.fillStyle='#9af9ed';dc.font='bold 68px monospace';dc.textAlign='center';dc.fillText(Math.max(1,Math.min(8,Math.ceil(p.speed/35))).toString(),128,77);dc.font='22px monospace';dc.fillText(`${Math.round(p.speed*.72)} KM/H`,128,109);dashTex.needsUpdate=true;}
 cockpitClip.setFromNormalAndCoplanarPoint(new THREE.Vector3(0,0,-1).applyQuaternion(driver.quaternion),new THREE.Vector3(0,0,-.6).applyQuaternion(driver.quaternion).add(driver.position));
 if(ticks%8===0)drawMap(race);
 if(!race.paused&&!race.done){for(let i=0;i<sparkCount;i++){sparkLife[i]-=dt;if(sparkLife[i]>0){sparkPositions[i*3+1]-=dt*.8;}else sparkPositions[i*3+1]=-1000;}if(!reduced&&p.speed>100&&(gp.keys[' ']||gp.nearest(p.x,p.y,point.h).dist>47)){for(let j=0;j<3;j++){const i=sparkIndex++%sparkCount,tail=new THREE.Vector3((Math.random()-.5)*1.5,.18,1.6).applyQuaternion(rig.quaternion).add(rig.position);sparkPositions.set(tail.toArray(),i*3);sparkLife[i]=.3+Math.random()*.3;}}sparkGeo.attributes.position.needsUpdate=true;}
 composer.render();
}};
buildTrack();loadCars();
