import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,Settings2,Volume2,VolumeX,Flag,ChevronRight} from 'lucide-react';
import {OriginButton} from '@/components/ui/origin-button';
import './tailwind.css';
import './style.css';
declare global {interface Window {PocketGP:any;race3D:any;}}
const click=(selector:string)=>(document.querySelector(selector) as HTMLButtonElement)?.click();
function Logo(){return <svg viewBox="230 230 800 800" role="img" aria-label="Your racing logo" className="lobby-logo"><defs><filter id="remove-white" colorInterpolationFilters="sRGB"><feColorMatrix type="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  -1 0 0 0 1"/></filter></defs><image href="public/assets/lobby/logo-source.png" width="1254" height="1254" filter="url(#remove-white)"/></svg>}
function App(){
 const [current,setCurrent]=useState('home'),[settings,setSettings]=useState(false),[sound,setSound]=useState(false),[snapshot,setSnapshot]=useState({races:0,wins:0,xp:0,credits:1200,ready:false});
 useEffect(()=>{const sync=()=>{const s=window.PocketGP?.save;if(s)setSnapshot({...s,ready:window.race3D?.loaded===2});const drawer=document.querySelector('#drawer') as HTMLElement;if(drawer?.hidden)setCurrent('home');};sync();const timer=setInterval(sync,350);return()=>clearInterval(timer);},[]);
 useEffect(()=>{document.body.classList.toggle('lobby-settings-open',settings);},[settings]);
 function navigate(key:string){setCurrent(key);setSettings(false);click(`[data-tab="${({home:'race',garage:'car',driver:'driver',career:'stats'} as Record<string,string>)[key]}"]`);}
 return <><div className="new-nav"><a href="#home" className="new-brand" onClick={e=>{e.preventDefault();navigate('home');}}><Logo/><span>MINI F1<small>TINY DRIVERS. BIG DREAMS.</small></span></a><div className="new-links" role="navigation" aria-label="Lobby navigation">{['home','garage','driver','career'].map(key=><OriginButton key={key} className={'nav-origin '+(current===key?'is-current':'')} aria-current={current===key?'page':undefined} onClick={()=>navigate(key)}>{key[0].toUpperCase()+key.slice(1)}</OriginButton>)}</div><div className="new-account"><span className="balance"><small>RACE CREDITS</small>{snapshot.credits.toLocaleString()}</span><OriginButton aria-label="Race settings" aria-expanded={settings} className="settings-origin" onClick={()=>{navigate('home');setSettings(!settings);}}><Settings2 size={18}/></OriginButton></div></div>
 <div className="home-ui"><div className="lobby-topline"><span><i/> YOUR PADDOCK</span><span>SEASON 01 / READY WHEN YOU ARE</span></div><div className="lobby-stats">{[[snapshot.races,'Races completed'],[snapshot.wins,'Race wins'],[String(Math.min(3,1+Math.floor(snapshot.xp/300))).padStart(2,'0'),'Driver level']].map(([n,label])=><div key={label} className="lobby-stat"><span>{label}</span><strong>{typeof n==='number'?String(n).padStart(2,'0'):n}</strong><div className="stat-rule"/></div>)}</div><div className="scene-copy"><span>SMALL CARS.</span><span>BIG RACING.</span></div><div className="hero-caption"><span>THE MINIATURE COLLECTION</span><span>01 — THE PADDOCK <ArrowUpRight size={13}/></span></div><div className="lobby-bottom"><button className="player-card" onClick={()=>navigate('driver')}><span className="player-symbol"><Flag size={23}/></span><span><strong>PLAYER ONE</strong><small>{['Rookie racer','Club contender','Grand prix ace'][Math.min(2,Math.floor(snapshot.xp/300))]} <span> / LEVEL {Math.min(3,1+Math.floor(snapshot.xp/300))}</span></small></span><ChevronRight size={18}/></button><div className="start-group"><span>3 LAPS · 6 DRIVERS · YOUR RACING LINE</span><OriginButton className="start-origin" loading={!snapshot.ready} onClick={()=>click('#start')}>{snapshot.ready?'Start race':'Preparing cars…'}<ArrowRight size={21}/></OriginButton></div></div><div className="lobby-foot"><span><i/> PROGRESS SAVED ON THIS DEVICE</span><OriginButton className="sound-origin" onClick={()=>{click('#sound');setSound(!sound);}}>{sound?<Volume2 size={15}/>:<VolumeX size={15}/>} Sound {sound?'on':'off'}</OriginButton></div></div></>;
}
const root=document.createElement('div');root.id='lobby-react';document.querySelector('#app')!.append(root);createRoot(root).render(<App/>);
